config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save ? (redirect_to restaurant_path(@restaurant.id)) : (render :new)
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def edit() end

  def show
    @review = Review.new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save ? (redirect_to restaurant_path(@restaurant.id)) : (render 'restaurants/show')
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit class:"btn btn-primary w-100" %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant</h1>

<div class="mx-auto max-w-xl">
  <%= render "form", restaurant: @restaurant %>
</div>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= link_to("#{restaurant.name}", restaurant_path(restaurant.id)) %></h2>
  <%= link_to "Delete",
            restaurant_path(restaurant.id),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
<% end %>
<br>
<br>
<%= link_to "Add a restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create a Restaurant</h1>

<div class="mx-auto max-w-xl">
  <%= render "form", restaurant: @restaurant %>
</div>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h3><%= @restaurant.category %></h3>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant.id) %>
<br>
<br>
<h4>Reviews</h4>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.rating %></p>
  <p><%= review.content %></p>
<% end %>
<h1>Leave a Review</h1>
<div class="mx-auto max-w-xl">
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class:"btn btn-primary w-100" %>
  <% end %>
</div>
<br>
<br>
<%= link_to 'Back to Restaurants', restaurants_path %>

app/views/reviews/new.html.erb
<h1>Create a Review</h1>

<div class="mx-auto max-w-xl">
  <%= simple_form_for([@restaurant, @review]) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit class:"btn btn-primary w-100" %>
  <% end %>
</div>

<%= link_to 'Back', restaurants_path %>